function SideBar() {
  return (
    <ul>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
      <li>itemsitemsitems</li>
    </ul>
  );
}

export default SideBar;
